config/routes.rb
Rails.application.routes.draw do
  resources :checkouts
  resources :books
  resources :users
  
  get '/', to: "users#home"
  get '/about', to: "users#about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :checkouts
    has_many :users, through: :checkouts
    validates :title, presence: true
    validates :author, presence: true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
    belongs_to :book
    belongs_to :user
    validates :user, presence: true
    validates :book, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :checkouts
    has_many :books, through: :checkouts
    
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    validates :address, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

   
    before_action :find_book, only: [:show, :edit, :update, :destroy]

    def index
        @books = Book.all
    end

    def show  
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.valid?
            @book.save
            redirect_to book_path(@book)
        else
            render :new
        end
    end
       
    
    def edit
    end
        

    def update
        @book.assign_attributes(book_params)
        if @book.valid?
            @book.save
            redirect_to book_path(@book)
        else
            render :edit
        end
    end


    def destroy
        @book.delete
        redirect_to books_path
    end


    private
    def find_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:title, :author)
    end


end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController

    before_action :find_checkout, only: [:update, :destroy]

    # def index
    #     @checkouts = Checkout.all
    # end

    # def show
    # end

    def new
        @checkout = Checkout.new
    end

    def create
        @checkout = Checkout.new(checkout_params)
        if @checkout.valid?
            @checkout.save
            redirect_to user_path(@checkout.user)
        else
            render :new
        end
    end

    private
    def find_checkout
        @checkout = Checkout.find(params[:id])
    end


    def checkout_params
        params.require(:checkout).permit(:user_id, :book_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]


    def about
        @users = User.count
        @books = Book.count
    end

    def home
        
    end

    def index
        @users = User.all
    end

    def show  
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            redirect_to user_path(@user)
        else
            render :new
        end
    end
       
    
    def edit
    end
        

    def update
        @user.assign_attributes(user_params)
        if @user.valid?
            @user.save
            redirect_to user_path(@user)
        else
            render :edit
        end
    end


    def destroy
        @user.delete
        redirect_to users_path
    end


    private
    def find_user
        @user = User.find(params[:id])
    end


    def user_params
        params.require(:user).permit(:name, :address)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_form.html.erb
<% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
        <%= msg %>
    <% end %>
<% end %>

<%= form_for @book do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h2> Edit book </h2>

<%= render partial: "book_form" %>

<br><br>
<%= button_to 'Cancel', book_path(@book), method: :get %>

app/views/books/index.html.erb
<h1> All books </h1>

Book titles: 
<ul>
    <% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %>
    <% end %>
</ul>

<br>
<%= button_to 'Add book', new_book_path, method: :get %>

app/views/books/new.html.erb
<h2> Add new book </h2>

<%= render partial: "book_form" %>

app/views/books/show.html.erb
<h2> Book details </h2>

Title: <%=  @book.title %><br>
Author: <%=  @book.author %><br>
Members checked out this book: 
    <ul>
        <% @book.users.each do |user| %>
          <li><%= link_to user.name, user_path(user) %></li>
        <% end %>
    </ul>

<br><br>
<%= button_to 'Back', books_path, method: :get %>
<br><br>
<%= button_to 'Edit book', edit_book_path(@book), method: :get %>
<br><br>
<%= button_to 'Add to checkout', new_checkout_path(@book.checkouts), method: :get %>
<br><br>
<%= button_to 'Delete book', book_path(@book), method: :delete, data: {confirm: 'እርግጠኛ ነህ?' } %>

app/views/checkouts/_checkout_form.html.erb
<% if @checkout.errors.any? %>
    <% @checkout.errors.full_messages.each do |msg| %>
    <%= msg %>
    <% end%>
<% end%>

<%= form_for @checkout do |f| %>
    <%= f.label :user %>
    <%= f.collection_select :user_id, User.all, :id, :name, include_blank: true %>
    <%= f.label :book %>
    <%= f.collection_select :book_id, Book.all, :id, :title, include_blank: true %>
    <%= f.submit %>
<% end%>

app/views/checkouts/index.html.erb
<h2> All checkouts </h2>

<ul>
    <% @checkouts.each do |c| %>
        <li><%= link_to c.user.name, checkout_path(c) %></li>
    <% end %>
</ul>

app/views/checkouts/new.html.erb
<h2> Add book to checkout </h2>

<%= render partial: "checkout_form" %>

app/views/checkouts/show.html.erb
<h2> Checkout details </h2>

Date: <%= @checkout.created_at %><br>
User name: <%= @checkout.user.name %><br>
Book title: <%= @checkout.book.title %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryMgt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :name  %>
<%= f.text_field :name  %>
<%= f.label :address  %>
<%= f.text_field :address  %>
<%= f.submit %>
<% end  %>

app/views/users/about.html.erb
<h1>About the library</h1>

Number of members: <%= @users %><br>
Number of books: <%= @books %>

<br>
<%= link_to 'Homepage', users_path %>

app/views/users/edit.html.erb
<h2> Edit member details </h2>

<%= render partial: "user_form" %>

<br><br><br>

<%= button_to 'Cancel', user_path(@user), method: :get %>

app/views/users/home.html.erb
<h1> Welcome</h1>

<%= link_to 'About', about_path %>

app/views/users/index.html.erb
<h1> All members list </h1>

<ul>
    <% @users.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
</ul>

<%= button_to 'Add new member', new_user_path, method: :get %>

app/views/users/new.html.erb
<h1> Add new member </h1>

<%= render partial: "user_form" %>

<br>

<%= button_to 'Cancel', users_path, method: :get %>

app/views/users/show.html.erb
<h1> Member details </h1>


<strong> Name: <%= @user.name%><br>
Address: <%= @user.address%> </strong> <br><br>

<% if !@user.books.empty? %>
    Books checked out: </strong>
    <ul>
        <% @user.books.each do |book| %>
            <li> Title: <%= book.title %> -
            <span> Author: <%= book.author %> </span></li>
        <% end %>
    </ul>
<% end %>

<br><br><br>
<%= button_to 'Edit user', edit_user_path, method: :get %>
<br>
<%= button_to 'Back', users_path, method: :get %>
<br>
<%= button_to 'Delete user', user_path(@user), method: :delete, data: {confirm: 'እርግጠኛ ነህ?' } %>
<br>
<%= button_to 'Add ckeckout', new_checkout_path, method: :get %>